### ISSUE TITLE
LCGS-examples and formulas - results

### ISSUE THREAD

**Issue by lars4509** [d702e20/OnTheFlyATL#113]
In the current examples there are no clear indication whether a formula's result is `true` or `false`, given some model. I believe that we might want to note that somewhere, so we ensure that we get the right results when testing.

**Comment by NicEastvillage** [comment]
We usually write that in the file name, e.g. `can_p1_guarantee_survival_FALSE.atl` is expected to give false.

**Comment by lars4509** [comment]
Damn, i didn't notice. My bad.
