### ISSUE TITLE
Find and write game structures in LCGS

### ISSUE THREAD

**Issue by NicEastvillage** [d702e20/OnTheFlyATL#25]
We need multiple LCGS programs for testing later. We can probably find some in the ATL paper or PRISM-games.

**Comment by NicEastvillage** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Find og skriv game structures i LCGS](https://trello.com/c/RASqk11w/61-find-og-skriv-game-structures-i-lcgs)

**Comment by GeneralDenmark** [comment]
I'll rewrite the [Rock-paper-scissors](http://www.prismmodelchecker.org/games/examples.php) example

**Comment by cogitantium** [comment]
I added the matching pennies example

**Comment by GeneralDenmark** [comment]
> I added the matching pennies example

Vi mangler Prism koden for dette eksempel
