### ISSUE TITLE
Potentiel bug

### ISSUE THREAD

**Issue by GeneralDenmark** [d702e20/OnTheFlyATL#70]
Jeg er ikke helt sikker på hvad @jenrik snakkede om, men runde ting betyder vist at det er implicit tegning. og det skal det ikke være? 

![image](https://user-images.githubusercontent.com/15718221/101613988-abb95300-3a0c-11eb-8abb-d5860ec89c87.png)

**Comment by NicEastvillage** [comment]
Dette er heldigvis kun en bug i grafprinteren. Selve grafen ser rigtig ud.
