### ISSUE TITLE
Despite invariant returns wrong result

### ISSUE THREAD

**Issue by MathiasMehl** [d702e20/OnTheFlyATL#97]
with lcgs program

```
player p = process;

label always_true = 1;

template process
    [act] 1;
endtemplate
```

and the formula in json 

```
{
    "despite invariant": {
        "players": [0],
        "formula": { 
            "proposition": 0
        }
    }
}
```

the result is `false`, but should be `true`

Ran with 
"run -- solver  --formula docs/lcgs/working-examples/despite_invariant.json --model docs/lcgs/working-examples/despite_invariant.lcgs  --model-type lcgs"

With despite_invariant being the name of the shown program/formula above

**Comment by NicEastvillage** [comment]
The cause might be race conditions. The formula `foo` and `!foo` also gives the same result, right now.
